INSERT INTO Ingredients (id, name, country, allergern) VALUES 
(001, "mango", "egypt", "none"),
(002, "pineapple", "costa rica", "ananas"),
(003, "orange", "spain", "none"),
(004, "passion fruit", "brasil", "none"),
(005, "strawberries", "france", "none"),
(006, "rawsberry", "france", "none"),
(007, "blueberry", "france", "none"),
(009, "kiwi", "new zeland", "kiwi"),
(010, "banana", "egypt", "none"),
(011, "cow milk", "france", "lactose")
(012, "oat milk", "france", "none");

INSERT TO Recipes(id, name, allergen, quantity, ingredients, time) VALUES
(001, "tropical", "pineapple", 75, "mango pineapple passion fruit", 2),
(002, "red fruits", "none", 75, "strawberry rawsberry blueberry", 2),
(003, "fruit salad", "kiwi, pineapple", 75, "pineapple strawberry kiwi", 2),
(004, "banawberries", "none", 75, "banana strawberry", 2)
(005, "orange juice", "none", 75, "orange", 1);
