INSERT INTO Ingredients (id, name, country, allergern) VALUES 
(001, "mango", "egypt", "none"),
(002, "pineapple", "costa rica", "ananas"),
(003, "orange", "spain", "none"),
(004, "passion fruit", "brasil", "none"),
(005, "strawberries", "france", "none"),
(006, "rawsberry", "france", "none"),
(007, "blueberry", "france", "none"),
(009, "kiwi", "new zeland", "kiwi"),
(010, "banana", "egypt", "none"),
(011, "cow milk", "france", "lactose")
(012, "oat milk", "france", "none");

