@startuml Diagram of MangoDB
Hide circle

entity Customer
{
    {static}<b>PK | email: VARCHAR(255)
    --
    <b>     | first_name: VARCHAR(255)
    <b>     | last_name: VARCHAR(255)
    <b>     | password: VARCHAR(255)
    <b>     | order_count: INT
    <b>     | loyalty_rank: [Bronze, Silver, Gold]
}

entity Order ##[dashed]
{
    {static}<b>PK | time: TIMESTAMP
    --
    <b>FK1 | customer_email: VARCHAR(255)
    <b>FK2 | mango_chef_email: VARCHAR(255)
    <b>     | price: FLOAT
    <b>     | status: [Pending, In Progress, Completed]
}

entity OrderMeal ##[dashed]
{
    {static}<b>PK ,FK1 | order_time: TIMESTAMP
    {static}<b>PK ,FK2 | meal_name: VARCHAR(255)
    --
    <b>     | quantity: INT
}

entity Meal ##[dashed]
{
    {static}<b>PK | name: VARCHAR(255)
    --
    <b>FK1 | order_time: TIMESTAMP
    <b>FK2 | recipe_name: VARCHAR(255)
    <b>     | price: FLOAT
    <b>     | preparation_time: TIME
}

entity RecipeMeal ##[dashed]
{
    {static}<b>PK , FK1 | recipe_name: VARCHAR(255)
    {static}<b>PK , FK2 | meal_name: VARCHAR(255)
    --
    <b>     | quantity: INT
}

entity Recipe ##[dashed]
{
    {static}<b>PK | name: VARCHAR(255)
    --
    <b>FK1 | ingredient_name: VARCHAR(255)
    <b>FK2 | tool_name: VARCHAR(255)
    <b>     | time: TIME
}

entity Step ##[dashed]
{
    {static}<b>PK , FK1 | recipe_name: VARCHAR(255)
    {static}<b>PK , FK2 | ingredient_name: VARCHAR(255)
    {static}<b>PK , FK3 | tool_name: VARCHAR(255)
    --
    <b>     | description: VARCHAR(255)
    <b>     | time: TIME
}

entity RecipeIngredient ##[dashed]
{
    {static}<b>PK , FK1 | recipe_name: VARCHAR(255)
    {static}<b>PK , FK2 | ingredient_name: VARCHAR(255)
    --
    <b>     | quantity: INT
}

entity RecipeTool ##[dashed]
{
    {static}<b>PK , FK1 | recipe_name: VARCHAR(255)
    {static}<b>PK , FK2 | tool_name: VARCHAR(255)
    --
    <b>     | quantity: INT
}

entity Ingredient
{
    {static}<b>PK | name: VARCHAR(255)
    --
    <b>     | price: FLOAT
    <b>     | calories : FLOAT
    <b>     | availability: BOOL
    <b>     | allergens: VARCHAR(255)
    <b>     | country: VARCHAR(255)
    <b>     | region: VARCHAR(255)
}

entity Tool
{
    {static}<b>PK | name: VARCHAR(255)
    --
    <b>     | price: FLOAT
    <b>     | availability: BOOL
}


entity SupplierCompany
{   
    {static}<b>PK | email: VARCHAR(255)
    --
    <b>     | name: VARCHAR(255)
    <b>     | password: VARCHAR(255)
    <b>     | address: VARCHAR(255)
    <b>     | price_category: [Low, Medium, High]
}

entity MangoChef
{
    {static}<b>PK | email: VARCHAR(255)
    --
    <b>     | first_name: VARCHAR(255)
    <b>     | last_name: VARCHAR(255)
    <b>     | password: VARCHAR(255)
    <b>     | working_hours: INT
    <b>     | salary: FLOAT
}

entity MangoManager
{
    {static}<b>PK | email: VARCHAR(255)
    --
    <b>     | first_name: VARCHAR(255)
    <b>     | last_name: VARCHAR(255)
    <b>     | password: VARCHAR(255)
    <b>     | working_hours: INT
    <b>     | salary: FLOAT
}

MangoManager ||.down-|{ SupplierCompany
MangoManager ||.up..|{ MangoChef
MangoChef ||-right-o{ Order

SupplierCompany ||.down-|{ Ingredient

Customer ||.down-o{ Order
Order  }o-down-|{ OrderMeal
OrderMeal }o-down-|{ Meal

Recipe }o-left-|{ RecipeIngredient
RecipeIngredient }o-down-|{ Ingredient
Recipe }o-right-|{ RecipeTool
RecipeTool }o-down-|{ Tool

Recipe }|-down-|{ Step
Meal }|-down-|{ RecipeMeal
Recipe }|-up-|{ RecipeMeal
@enduml