@startuml Diagram of MangoDB
Hide circle

entity Customer
{
    {static}<b>PK | email: VARCHAR(255)
    --
    <b>     | first_name: VARCHAR(255)
    <b>     | last_name: VARCHAR(255)
    <b>     | password: VARCHAR(255)
    <b>     | loyalty_rank: [Bronze, Silver, Gold]
}

entity Order
{
    {static}<b>PK | time: TIMESTAMP
    --
    <b>FK1 | customer_email: VARCHAR(255)
    <b>FK2 | mango_chef_email: VARCHAR(255)
    <b>     | price: FLOAT
    <b>     | status: [Pending, In Progress, Completed]
}

entity OrderRecipe ##[dashed]
{
    {static}<b>PK , FK1 | order_time: TIMESTAMP
    {static}<b>PK , FK2 | recipe_name: VARCHAR(255)
    --
    <b>     | quantity: INT
}

entity Recipe
{
    {static}<b>PK | name: VARCHAR(255)
    --
}

entity Step ##[dashed]
{
    {static}<b>PK , FK1 | recipe_name: VARCHAR(255)
    --
    <b>     | description: VARCHAR(255)
    <b>     | time: TIME
}

entity RecipeIngredient ##[dashed]
{
    {static}<b>PK , FK1 | recipe_name: VARCHAR(255)
    {static}<b>PK , FK2 | ingredient_name: VARCHAR(255)
    --
    <b>     | quantity: INT
}

entity RecipeTool ##[dashed]
{
    {static}<b>PK , FK1 | recipe_name: VARCHAR(255)
    {static}<b>PK , FK2 | tool_name: VARCHAR(255)
    --
    <b>     | quantity: INT
}

entity Ingredient
{
    {static}<b>PK | name: VARCHAR(255)
    --
    <b>FK1 | supplier_email: VARCHAR(255) 
    <b>     | price: FLOAT
    <b>     | calories : FLOAT
    <b>     | in_stock: INT
    <b>     | allergen: VARCHAR(255)
    <b>     | country: VARCHAR(255)
}

entity Tool
{
    {static}<b>PK | name: VARCHAR(255)
    --
    <b>     | price: FLOAT
    <b>     | in_stock: INT
}


entity SupplierCompany
{   
    {static}<b>PK | email: VARCHAR(255)
    --
    <b>FK1 | manager_email: VARCHAR(255)
    <b>     | name: VARCHAR(255)
    <b>     | password: VARCHAR(255)
    <b>     | address: VARCHAR(255)
    <b>     | price_category: [Low, Medium, High]
}

entity MangoChef
{
    {static}<b>PK | email: VARCHAR(255)
    --
    <b>FK1 | manager_email: VARCHAR(255)
    <b>     | first_name: VARCHAR(255)
    <b>     | last_name: VARCHAR(255)
    <b>     | password: VARCHAR(255)
    <b>     | working_hours: TIME
    <b>     | salary: FLOAT
}

entity MangoManager
{
    {static}<b>PK | email: VARCHAR(255)
    --
    <b>     | first_name: VARCHAR(255)
    <b>     | last_name: VARCHAR(255)
    <b>     | password: VARCHAR(255)
    <b>     | working_hours: TIME
    <b>     | salary: FLOAT
}

MangoManager ||-down-o{ SupplierCompany
MangoManager ||-up-o{ MangoChef
MangoChef ||-right-o{ Order

SupplierCompany ||-down-o{ Ingredient

Customer ||-down-o{ Order
Order  ||-down-|{ OrderRecipe

Recipe ||-down-|{ RecipeIngredient
RecipeIngredient }o-up-|| Ingredient
Recipe ||-down-|{ RecipeTool
RecipeTool }o-up-|| Tool

Recipe ||-down-|{ Step
Recipe ||-up-|{ OrderRecipe
@enduml