global using System.Text;
global using ConsoleAppVisuals;
global using ConsoleAppVisuals.AnimatedElements;
global using ConsoleAppVisuals.Enums;
global using ConsoleAppVisuals.InteractiveElements;
global using ConsoleAppVisuals.PassiveElements;
global using SharpHash.Base;
global using Npgsql;
global using dotenv.net;